// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

function getRandomInt(max) {
  return Math.floor(Math.random() * max);
}

describe('RegistrationAndLogout', function () {
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  this.timeout(10000)
  afterEach(async function() {
    await driver.quit();
  })
  const name = `name${getRandomInt(100)}`;
  const email = `email${getRandomInt(100)}@gmail.com`;
  it('RegistrationAndLogoutv2', async function() {
    await driver.get("http://localhost:8080/register")
    await driver.manage().window().setRect({ width: 864, height: 668 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys(name)
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys(email)
    await driver.findElement(By.id("password")).sendKeys("Vbajkjubz16")
    await driver.findElement(By.id("confirm")).sendKeys("Vbajkjubz16")
    await driver.findElement(By.id("register")).click()
    await driver.findElement(By.css(".list-group-item:nth-child(4)")).click()
    await driver.findElement(By.id("username")).sendKeys("Kadmus16")
    await driver.findElement(By.id("password")).sendKeys("Vbajkjubz16")
  })
})
